(define m (/ 2 (+ 1 (sqrt 5))))
(define (cont-frac n d k)
  (define (iter i result)
    (if (= i 0)
        result
        (iter (- i 1) (/ (n i) (+ (d i) result)))))
  (iter k 0))                                                                                                                                       
(define (value k)
  (cont-frac (lambda (i) 1.0)
              (lambda (i) 1.0)
              k))
(define (close-enough? x)
  (< (abs (- x m)) 0.0001)) 
(define (golden-ratio? k)
    (if (close-enough? (value k))
        (display "yes")
        (display "no")))
(define (count-k)
  (define (iter i)
    (if (close-enough? (value i))
        i
        (iter (+ i 1))))
  (iter 1))