(define (curt-iter guess x)
  (if (guess-enough? guess x)
      guess
      (curt-iter (improve guess x) x)))
(define (improve guess x)
  (/ (+ (/ x (square guess)) (* 2 guess)) 3))
(define (square x)
  (* x x))
(define (guess-enough? guess x)
  (< (abs (/ (- (/ x (cube guess)) 1) 3)) 0.000001))
(define (cube x)
  (* x (* x x)))
(define (curtx x)
  (curt-iter 1.0 x))