(define (fast-multi a b)
  (cond ((= b 0) 0)
        ((= b 1) a)
        ((even b) (fast-multi (double a) (halve b)))
        (else (+ a (fast-multi a (- b 1))))))
(define (halve n)
  (/ n 2))
(define (double n)
  (* n 2))
(define (even n)
  (= (remainder n 2) 0))