(define tolerance 0.00001)
(define (fix-point f first-guess)
  (define (try guess)
    (let ((next (f guess)))
      (if (close-enough? next guess)
          next
          (try next))))
  (try first-guess))
(define (close-enough? m n)
  (< (abs (- m n)) tolerance))