(define (multi a b)
  (multi a b a))
(define (fast-multi a b m)
  (cond ((= b 0) 0)
        ((= b 1) m)
        ((even b) (multi a (halve b) (double m)))
        (else (+ a (multi a (- b 1) m)))))
(define (double x)
  (* x 2))
(define (halve x)
  (/ x 2))
(define (even x)
  (= (remainder x 2) 0))