(define (sqrt-iter guess x)
  (if (guess-enough? guess x)
      guess
      (sqrt-iter (improve guess x) x)))
(define (improve guess x)
  (average guess (/ x guess)))
(define (average x y)
  (/ (+ x y) 2))
(define (square x)
  (* x x))
(define (guess-enough? guess x)
  (< (abs (/ (- (/ x (square guess)) 1) 2)) 0.00001))
(define (sqrtx x)
  (sqrt-iter 1.0 x))