(require srfi/19)
(define (smallest-divisor n)
  (find-divisor n 2))
(define (find-divisor n test-divisor)
  (cond ((> (square test-divisor) n) n)
        ((divides test-divisor n) test-divisor)
        (else (find-divisor n (next test-divisor)))))
(define (next m)
  (cond ((= m 2) 3)
        (else (+ m 2))))
(define (divides a b)
  (= (remainder b a) 0))
(define (square x)
  (* x x))
(define (prime-number n)
  (= (smallest-divisor n) n))
(define (time-prime-test n)
  (newline)
  (display n)
  (start-prime-test n (current-time)))
(define (start-prime-test n start-time)
  (if (prime-number n)
      (report-prime (time-difference (current-time) start-time))))
(define (report-prime elapsed-time)
  (display "***")
  (display elapsed-time))
(define (search-for-primes start count)
  (cond ((= count 0)
         (newline)
         (display "end")
         (newline))
        ((enev start) (search-for-primes (+ start 1) count))
        ((prime-number start)
         (time-prime-test start)
         (search-for-primes (+ start 2) (- count 1)))
        (else (search-for-primes (+ start 2) count))))
(define (enev n)
  (= (remainder n 2) 0))
  