(define (f n)
  (cond ((< n 1) 0)
        ((= n 1) 1)
        ((= n 2) 2)
        (else (+ (f (- n 1)) (f-two (- n 2)) (f-three (- n 3))))))
(define (f-two y)
  (* 2 (f y)))
(define (f-three z)
  (* 3 (f z)))