(define (square-tree item)
  (map (lambda (tree) 
          (if (pair? tree)
              (cons (square-tree (car tree))
                    (square-tree (cdr tree)))
              (square tree)))
       item))
(define (square x)
  (* x x))